#!groovy
def awsCredentials = [[$class: 'AmazonWebServicesCredentialsBinding',
                       credentialsId: 'DPRC_AWS_CREDS']]

pipeline {
    environment {
        AWS_REGION = 'us-west-2'
    }
    agent any
    triggers {
        githubPush()
    }
    stages {
        stage('Test') {

            steps {

                dir("backend") {


                    checkout([

                       $class: 'GitSCM',
                       branches: [[name: 'refs/heads/master']],
                       doGenerateSubmoduleConfigurations: false,
                       extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'backend']],
                       submoduleCfg: [],
                       userRemoteConfigs: [[credentialsId: 'githubaccount', url: 'https://github.com/Fontaineconsult/accessiblebookchecker']]



                    ])


                }


                sh 'ls'
                sh 'ls /backend'
            }

        }

    }

}

