#!groovy
def awsCredentials = [[$class: 'AmazonWebServicesCredentialsBinding',
                       credentialsId: 'DPRC_AWS_CREDS']]

pipeline {
    environment {
        AWS_REGION = 'us-west-2'
    }
    agent any
    triggers {
        githubPush()
    }
    stages {
        stage('Test') {

            steps {
                sh 'ls'
            }

        }

    }

}

